import { useState, useMemo } from "react";
import type { JobPostingResponsePRF } from "@/features/jobs/types/job.types";
import { EditStep01 } from "./prf-edit/EditStep01";
import { EditStep02 } from "./prf-edit/EditStep02";
import { EditStep03 } from "./prf-edit/EditStep03";
import useSubmitEditForm from "../hooks/useSubmitEditForm";

interface PRFEditFormProps {
  initialData: JobPostingResponsePRF;
}

export default function PRFEditForm({ initialData }: PRFEditFormProps) {
  const [formData, setFormData] = useState(initialData);
  const [step, setStep] = useState(1);
  const [maxStepVisited, setMaxStepVisited] = useState(1);
  const { handleSubmit, loading, errors } = useSubmitEditForm({ formData });

  const stepErrorMapping = useMemo(() => {
    const step1Fields = [
      "job_posting.job_title",
      "job_posting.target_start_date",
      "number_of_vacancies",
      "business_unit",
      "job_posting.reason_for_posting",
      "job_posting.other_reason_for_posting",
      "job_posting.department_name",
      "immediate_supervisor",
      "hiring_managers",
    ];

    const step2Fields = [
      "category",
      "position",
      "working_site",
      "job_posting.work_setup",
      "job_posting.employment_type",
      "work_schedule_from",
      "work_schedule_to",
      "job_posting.description",
      "job_posting.responsibilities",
      "job_posting.qualifications",
      "non_negotiables",
    ];

    const step3Fields = [
      "salary_budget",
      "is_salary_range",
      "job_posting.min_salary",
      "job_posting.max_salary",
      "assessment_required",
      "assessment_types",
      "other_assessment",
      "hardware_requirements",
      "software_requirements",
    ];

    return { step1Fields, step2Fields, step3Fields };
  }, []);

  const hasStepError = (stepNumber: number) => {
    if (!errors || Object.keys(errors).length === 0) return false;

    const { step1Fields, step2Fields, step3Fields } = stepErrorMapping;
    let fieldsToCheck: string[] = [];

    if (stepNumber === 1) fieldsToCheck = step1Fields;
    else if (stepNumber === 2) fieldsToCheck = step2Fields;
    else if (stepNumber === 3) fieldsToCheck = step3Fields;

    return fieldsToCheck.some((field) => {
      if (field.includes(".")) {
        const [parent, child] = field.split(".");
        return errors[parent]?.[child];
      }
      return errors[field];
    });
  };

  const handleInputChange = (
    field: keyof JobPostingResponsePRF,
    value: string | number | boolean
  ) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const handleHiringManagerChange = (index: number, value: string) => {
    const updatedManagers = [...(formData.hiring_managers || [])];
    updatedManagers[index] =
      value === "no-hiring-manager" ? 0 : parseInt(value);
    setFormData((prev) => ({ ...prev, hiring_managers: updatedManagers }));
  };

  const handleAssessmentTypeToggle = (type: string) => {
    setFormData((prev) => {
      const currentTypes = Array.isArray(prev.assessment_types)
        ? prev.assessment_types
        : [];

      const isSelected = currentTypes.some(
        (at: { id: number; name: string }) => at.name === type
      );

      let updatedTypes;
      if (isSelected) {
        updatedTypes = currentTypes.filter(
          (at: { id: number; name: string }) => at.name !== type
        );
      } else {
        // id will be generated by backend
        updatedTypes = [...currentTypes, { id: 0, name: type }];
      }
      return {
        ...prev,
        assessment_types: updatedTypes,
      };
    });
  };

  const handleRequirementsToggle = (requirement: string) => {
    setFormData((prev) => {
      const currentTypes = Array.isArray(prev.hardware_requirements)
        ? prev.hardware_requirements
        : [];

      const isSelected = currentTypes.some((r) => r.name === requirement);

      let updatedTypes;
      if (isSelected) {
        updatedTypes = currentTypes.filter(
          (r: { id: number; name: string }) => r.name !== requirement
        );
      } else {
        // id will be generated by backend
        updatedTypes = [...currentTypes, { id: 0, name: requirement }];
      }
      return {
        ...prev,
        hardware_requirements: updatedTypes,
      };
    });
  };

  const handleSoftwareToggle = (requirement: string) => {
    setFormData((prev) => {
      const currentTypes = Array.isArray(prev.software_requirements)
        ? prev.software_requirements
        : [];

      const isSelected = currentTypes.some((r) => r.name === requirement);
      let updatedTypes;
      if (isSelected) {
        updatedTypes = currentTypes.filter(
          (r: { id: number; name: string }) => r.name !== requirement
        );
      } else {
        // id will be generated by backend
        updatedTypes = [...currentTypes, { id: 0, name: requirement }];
      }
      return {
        ...prev,
        software_requirements: updatedTypes,
      };
    });
  };

  const goToNextStep = () => {
    setStep((prev) => {
      const nextStep = Math.min(prev + 1, 3);
      setMaxStepVisited((currentMax) => Math.max(currentMax, nextStep));
      return nextStep;
    });
  };

  const goToPreviousStep = () => setStep((prev) => Math.max(prev - 1, 1));

  return (
    <div className="space-y-6">
      {/* Step Navigation Header */}
      <div className="flex space-x-0 border border-gray-300 rounded-md overflow-hidden mb-8">
        {["Step 01", "Step 02", "Step 03"].map((label, i) => {
          const stepNum = i + 1;
          const hasError = hasStepError(stepNum);
          const isActiveStep = stepNum === step;

          return (
            <div
              key={i}
              className={`flex-1 text-center py-2 text-sm font-semibold relative ${
                hasError && !isActiveStep
                  ? "bg-red-500 text-white"
                  : isActiveStep
                  ? "bg-[#0056D2] text-white"
                  : "bg-white text-gray-500"
              } ${
                stepNum <= maxStepVisited && !isActiveStep
                  ? "cursor-pointer hover:opacity-90"
                  : ""
              }`}
              onClick={() => {
                if (stepNum <= maxStepVisited && !isActiveStep) {
                  setStep(stepNum);
                }
              }}
            >
              {label}
              {hasError && !isActiveStep && (
                <span className="ml-1 text-xs">⚠</span>
              )}
              {i < 2 && (
                <span className="absolute right-0 top-0 h-full w-px bg-gray-300" />
              )}
            </div>
          );
        })}
      </div>

      {/* Step Components */}
      {step === 1 && (
        <EditStep01
          goToNextStep={goToNextStep}
          formData={formData}
          handleInputChange={handleInputChange}
          handleHiringManagerChange={handleHiringManagerChange}
          setFormData={setFormData}
          errors={errors}
        />
      )}
      {step === 2 && (
        <EditStep02
          goToNextStep={goToNextStep}
          goToPreviousStep={goToPreviousStep}
          formData={formData}
          handleInputChange={handleInputChange}
          setFormData={setFormData}
          errors={errors}
        />
      )}
      {step === 3 && (
        <EditStep03
          handleSubmit={handleSubmit}
          goToPreviousStep={goToPreviousStep}
          formData={formData}
          handleInputChange={handleInputChange}
          handleAssessmentTypeToggle={handleAssessmentTypeToggle}
          handleRequirementsToggle={handleRequirementsToggle}
          handleSoftwareToggle={handleSoftwareToggle}
          loading={loading}
        />
      )}
    </div>
  );
}
