import { useState } from "react";
import type { JobPostingResponsePRF } from "@/features/jobs/types/jobTypes";
import { EditStep01 } from "./edit/EditStep01";
import { EditStep02 } from "./edit/EditStep02";
import { EditStep03 } from "./edit/EditStep03";
import useSubmitEditForm from "../hooks/useSubmitEditForm";

interface PRFEditFormProps {
  initialData: JobPostingResponsePRF;
}

export default function PRFEditForm({ initialData }: PRFEditFormProps) {
  const [formData, setFormData] = useState(initialData);
  const [step, setStep] = useState(1);
  const [maxStepVisited, setMaxStepVisited] = useState(1);
  const { handleSubmit, loading, errors } = useSubmitEditForm({ formData });

  const handleInputChange = (
    field: keyof JobPostingResponsePRF,
    value: string | number | boolean
  ) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const handleHiringManagerChange = (index: number, value: string) => {
    const updatedManagers = [...(formData.hiring_managers || [])];
    updatedManagers[index] =
      value === "no-hiring-manager" ? 0 : parseInt(value);
    setFormData((prev) => ({ ...prev, hiring_managers: updatedManagers }));
  };

  const handleAssessmentTypeToggle = (type: string) => {
    setFormData((prev) => {
      const currentTypes = Array.isArray(prev.assessment_types)
        ? prev.assessment_types
        : [];

      const isSelected = currentTypes.some(
        (at: { id: number; name: string }) => at.name === type
      );

      let updatedTypes;
      if (isSelected) {
        // Remove the type
        updatedTypes = currentTypes.filter(
          (at: { id: number; name: string }) => at.name !== type
        );
      } else {
        // Add the type (id will be generated by backend)
        updatedTypes = [...currentTypes, { id: 0, name: type }];
      }
      return {
        ...prev,
        assessment_types: updatedTypes,
      };
    });
  };

  const handleRequirementsToggle = (requirement: string) => {
    setFormData((prev) => {
      const currentTypes = Array.isArray(prev.hardware_requirements)
        ? prev.hardware_requirements
        : [];

      const isSelected = currentTypes.some((r) => r.name === requirement);

      let updatedTypes;
      if (isSelected) {
        // Remove the requirement
        updatedTypes = currentTypes.filter(
          (r: { id: number; name: string }) => r.name !== requirement
        );
      } else {
        // Add the requirement (id will be generated by backend)
        updatedTypes = [...currentTypes, { id: 0, name: requirement }];
      }
      return {
        ...prev,
        hardware_requirements: updatedTypes,
      };
    });
  };

  const handleSoftwareToggle = (requirement: string) => {
    setFormData((prev) => {
      const currentTypes = Array.isArray(prev.software_requirements)
        ? prev.software_requirements
        : [];

      const isSelected = currentTypes.some((r) => r.name === requirement);
      let updatedTypes;
      if (isSelected) {
        // Remove the requirement
        updatedTypes = currentTypes.filter(
          (r: { id: number; name: string }) => r.name !== requirement
        );
      } else {
        // Add the requirement (id will be generated by backend)
        updatedTypes = [...currentTypes, { id: 0, name: requirement }];
      }
      return {
        ...prev,
        software_requirements: updatedTypes,
      };
    });
  };

  const goToNextStep = () => {
    setStep((prev) => {
      const nextStep = Math.min(prev + 1, 3);
      setMaxStepVisited((currentMax) => Math.max(currentMax, nextStep));
      return nextStep;
    });
  };

  const goToPreviousStep = () => setStep((prev) => Math.max(prev - 1, 1));

  return (
    <div className="p-6 space-y-6">
      {/* Step Navigation Header */}
      <div className="flex space-x-0 border border-gray-300 rounded-md overflow-hidden mb-8">
        {["Step 01", "Step 02", "Step 03"].map((label, i) => (
          <div
            key={i}
            className={`flex-1 text-center py-2 text-sm font-semibold relative ${
              i + 1 === step
                ? "bg-[#0056D2] text-white"
                : "bg-white text-gray-500"
            } ${
              i + 1 <= maxStepVisited && i + 1 !== step
                ? "cursor-pointer hover:bg-gray-100"
                : ""
            }`}
            onClick={() => {
              if (i + 1 <= maxStepVisited && i + 1 !== step) {
                setStep(i + 1);
              }
            }}
          >
            {label}
            {i < 2 && (
              <span className="absolute right-0 top-0 h-full w-px bg-gray-300" />
            )}
          </div>
        ))}
      </div>

      {/* Step Components */}
      {step === 1 && (
        <EditStep01
          goToNextStep={goToNextStep}
          formData={formData}
          handleInputChange={handleInputChange}
          handleHiringManagerChange={handleHiringManagerChange}
          setFormData={setFormData}
          errors={errors}
        />
      )}
      {step === 2 && (
        <EditStep02
          goToNextStep={goToNextStep}
          goToPreviousStep={goToPreviousStep}
          formData={formData}
          handleInputChange={handleInputChange}
          setFormData={setFormData}
          errors={errors}
        />
      )}
      {step === 3 && (
        <EditStep03
          handleSubmit={handleSubmit}
          goToPreviousStep={goToPreviousStep}
          formData={formData}
          handleInputChange={handleInputChange}
          handleAssessmentTypeToggle={handleAssessmentTypeToggle}
          handleRequirementsToggle={handleRequirementsToggle}
          handleSoftwareToggle={handleSoftwareToggle}
          loading={loading}
        />
      )}
    </div>
  );
}
