import type { Job } from "../features/jobs/types/Job";

export async function getJobs(): Promise<Job[]> {
  // TODO: Replace with actual API call
  return [
    {
      id: "1",
      title: "Project Manager",
      created: "Jun 01, 2024",
      totalCandidates: 10,
      vacancies: 2,
      status: "Published",
      department: "CI",
      employmentType: "Full time",
    },
    {
      id: "2",
      title: "Social Content Manager",
      created: "Jun 01, 2024",
      totalCandidates: 5,
      vacancies: 1,
      status: "Published",
      department: "Marketing",
      employmentType: "Full time",
    },
    {
      id: "3",
      title: "Senior UI UX Designer",
      created: "Jul 29, 2024",
      totalCandidates: 12,
      vacancies: 3,
      status: "Published",
      department: "CI",
      employmentType: "Full time",
    },
    {
      id: "4",
      title: "Lead Developer",
      created: "Dec 24, 2022",
      totalCandidates: 12,
      vacancies: 4,
      status: "Pending",
      department: "CI",
      employmentType: "Full time",
    },
    {
      id: "5",
      title: "Customer Support",
      created: "Jul 22, 2023",
      totalCandidates: 21,
      vacancies: 5,
      status: "Published",
      department: "CI",
      employmentType: "Full time",
    },
    {
      id: "6",
      title: "QA Engineer",
      created: "Jan 26, 2022",
      totalCandidates: 18,
      vacancies: 1,
      status: "Closed",
      department: "CI",
      employmentType: "Full time",
    },
    {
      id: "7",
      title: "Human Resources Coordinator",
      created: "Apr 21, 2023",
      totalCandidates: 5,
      vacancies: 1,
      status: "Closed",
      department: "HR",
      employmentType: "Full time",
    },
    {
      id: "8",
      title: "Operations Manager",
      created: "Feb 02, 2020",
      totalCandidates: 10,
      vacancies: 1,
      status: "Closed",
      department: "HR",
      employmentType: "Full time",
    },
    {
      id: "9",
      title: "Social Media Manager",
      created: "Mar 21, 2020",
      totalCandidates: 2,
      vacancies: 1,
      status: "Closed",
      department: "Marketing",
      employmentType: "Full time",
    },
    {
      id: "10",
      title: "Marketing Specialist",
      created: "Apr 27, 2024",
      totalCandidates: 4,
      vacancies: 2,
      status: "Draft",
      department: "Marketing",
      employmentType: "Full time",
    },
  ];
}
