import type { PositionFormData } from "../types/externalPosting.types";

export const getDefaultFormData = (): PositionFormData => ({
  client: null,
  education_level: null,
  job_posting: {
    job_title: null,
    department: null,
    experience_level: null,
    employment_type: null,
    number_of_vacancies: null,
    work_setup: null,
    target_start_date: null,
    reason_for_posting: null,
    other_reason_for_posting: null,
    min_salary: null,
    max_salary: null,
    description: null,
    responsibilities: null,
    qualifications: null,
    working_site: null,
    work_schedule_from: null,
    work_schedule_to: null,
  },
  application_form: {
    application_form: {
      name: "optional",
      birth_date: "optional",
      gender: "optional",
      primary_contact_number: "optional",
      secondary_contact_number: "optional",
      email: "optional",
      linkedin_profile: "optional",
      address: "optional",
      expected_salary: "optional",
      willing_to_work_onsite: "optional",
      photo_2x2: "optional",
      upload_med_cert: "optional",
      preferred_interview_schedule: "optional",
      education_attained: "optional",
      year_graduated: "optional",
      university: "optional",
      course: "optional",
      work_experience: "optional",
      how_did_you_hear_about_us: "optional",
      agreement: "optional",
      signature: "optional",
    },
    non_negotiable: { non_negotiable: [] },
    questionnaire: { name: null, template: false, sections: [] },
  },
  pipeline: [],
  locations: [],
  batches: [],
});
